name: CD

on:
  release:
    types: [ created ]

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 8.0.432-amzn
          sdk install maven 3.6.3
          mvn package

      - name: Compress the directory
        run: |
          TAG_NAME=${GITHUB_REF_NAME} >> $GITHUB_ENV
          mv JMugen.Debug/target/JMugen.Debug-0.0.1-SNAPSHOT.jar "jmugen-${TAG_NAME}.jar"
          zip -r "jmugen-${TAG_NAME}.zip" resource "jmugen-${TAG_NAME}.jar"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: jmugen-${{ TAG_NAME }}.zip
