name: CD

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 17.0.14-amzn
          sdk install maven 3.6.3
          mvn package

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y tree tar gzip build-essential wget libfuse-dev

      - name: Download and install AppImageTool
        run: |
          ARCH=`uname -m`
          wget "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$ARCH.AppImage"
          chmod +x "appimagetool-$ARCH.AppImage"
          sudo mv "appimagetool-$ARCH.AppImage" /usr/local/bin/appimagetool          

      - name: Set TAG_NAME
        run: echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: AppImage
        run: |
          make app-image

#          appimagetool dist/jmugen*
#          mv dist/*.AppImage jmugen-${{ env.TAG_NAME }}.AppImage

      - name: Prepare release
        run: |
          # resource
          zip -r resource.zip resource

          # jar
          mv JMugen.Debug/target/JMugen.Debug-0.0.1-SNAPSHOT.jar jmugen-${TAG_NAME}.jar

          # tar.gz of app-image
          (cd dist && tar cfzv ../jmugen-${TAG_NAME}.tar.gz jmugen-${TAG_NAME}*)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: resource.zip jmugen-${{ env.TAG_NAME }}.jar jmugen-${{ env.TAG_NAME }}.tar.gz
