name: CD

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 17.0.14-amzn
          sdk install maven 3.6.3
          mvn package

      - name: Set TAG_NAME
        run: echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Compress
        run: |
          mv JMugen.Debug/target/JMugen.Debug-0.0.1-SNAPSHOT.jar jmugen.jar
          zip -r "jmugen-${TAG_NAME}.zip" resource jmugen.jar

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential wget libfuse-dev

      - name: Download and install AppImageTool
        run: |
          ARCH=`uname -m`
          wget "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$ARCH.AppImage"
          chmod +x "AppImageTool-$ARCH.AppImage"
          sudo mv "AppImageTool-$ARCH.AppImage" /usr/local/bin/appimagetool          
          
      - name: AppImage
        run: |
          DTMP=`mktemp -d`
          cp jmugen.jar $DTMP/jmugen.jar
          jpackage --input $DTMP \
          --name JMugen \
          --main-jar jmugen.jar \
          --type app-image \
          --jlink-options "--strip-native-commands --strip-debug --no-man-pages --no-header-files"
          appimagetool $DTMP/JMugen
          mv $DTMP/JMugen*.AppImage jmugen-${{ env.TAG_NAME }}.AppImage

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: jmugen-${{ env.TAG_NAME }}.zip jmugen-${{ env.TAG_NAME }}.AppImage
